#!/usr/bin/env python3

""" This file contains main configuration of Data Analyzer Chart.
"""

from collections import namedtuple

TagRepr = namedtuple('Tag', ['name', 'text', 'title'])

TAGS = [TagRepr('c++', 'c++', 'cpp'),
        TagRepr('java', 'java', 'java'),
        TagRepr('python', 'python', 'python'),
        TagRepr('sap', 'sap', 'sap'),
        TagRepr('bash', 'bash', 'bash'),
        TagRepr('perl', 'perl', 'perl'),
        TagRepr('ruby', 'ruby', 'ruby'),
        TagRepr('javascript', 'javascript', 'javascript'),
        TagRepr('php', 'php', 'php'),
        TagRepr('1c', '1c', 'onec'),
        TagRepr('c#', 'c#', 'csharp'),

        TagRepr('algol','algol','algol'),
        TagRepr('ada','ada','ada'),
        TagRepr('basic','basic','basic'),
        TagRepr('cobol','cobol','cobol'),
        TagRepr('lisp','lisp','lisp'),
        TagRepr('erlang','erlang','erlang'),
        TagRepr('go','go','go'),
        TagRepr('groovy','groovy','groovy'),
        TagRepr('haskell','haskell','haskell'),
        TagRepr('lua','lua','lua'),
        TagRepr('matlab','matlab','matlab'),
        TagRepr('pascal','pascal','pascal'),
        TagRepr('rust','rust','rust'),
        TagRepr('scala','scala','scala'),
        TagRepr('smalltalk','smalltalk','smalltalk'),
        TagRepr('swift','swift','swift'),
        TagRepr('sql','sql','sql'),
        TagRepr('VBA','vba','vba'),
        # Databases...
        # Os...
        # Position...

        TagRepr('agile','agile','agile'),
        TagRepr('ajax','ajax','ajax'),
        TagRepr('amd','amd','amd'),
        TagRepr('assembler','assembler','assembler'),
        TagRepr('awk','awk','awk'),
        TagRepr('backend','backend','backend'),
        TagRepr('canvas','canvas','canvas'),
        TagRepr('cmake','cmake','cmake'),
        TagRepr('cms','cms','cms'),
        TagRepr('css','css','css'),
        TagRepr('cuda','cuda','cuda'),
        TagRepr('cvs','cvs','cvs'),
        TagRepr('delphi','delphi','delphi'),
        TagRepr('django','django','django'),
        TagRepr('dll','dll','dll'),
        TagRepr('dns','dns','dns'),
        TagRepr('dom','dom','dom'),
        TagRepr('freebsd','freebsd','freebsd'),
        TagRepr('gcc','gcc','gcc'),
        TagRepr('gdb','gdb','gdb'),
        TagRepr('git','git','git'),
        TagRepr('github','github','github'),
        TagRepr('gps','gps','gps'),
        TagRepr('gpu','gpu','gpu'),
        TagRepr('ios','ios','ios'),
        TagRepr('innodb','innodb','innodb'),
        TagRepr('ipc','ipc','ipc'),
        TagRepr('iptables','iptables','iptables'),
        TagRepr('jira','jira','jira'),
        TagRepr('joomla','joomla','joomla'),
        TagRepr('jquery','jquery','jquery'),
        TagRepr('jruby','jruby','jruby'),
        TagRepr('json','json','json'),
        TagRepr('junit','junit','junit'),
        TagRepr('kanban','kanban','kanban'),
        TagRepr('linux','linux','linux'),
        TagRepr('lua','lua','lua'),
        TagRepr('mac','mac','mac'),
        TagRepr('memcached','memcached','memcached'),
        TagRepr('mysql','mysql','mysql'),
        TagRepr('nginx','nginx','nginx'),
        TagRepr('apache','apache','apache'),
        TagRepr('nix','nix','nix'),
        TagRepr('postgresql','postgresql','postgresql'),
        TagRepr('posix','posix','posix'),
        TagRepr('redis','redis','redis'),
        TagRepr('redmine','redmine','redmine'),
        TagRepr('saas','saas','saas'),
        TagRepr('scala','scala','scala'),
        TagRepr('scipy','scipy','scipy'),
        TagRepr('scrum','scrum','scrum'),
        TagRepr('search','search','search'),
        TagRepr('seo','seo','seo'),
        TagRepr('shell','shell','shell'),
        TagRepr('soap','soap','soap'),
        TagRepr('socket','socket','socket'),
        TagRepr('sphinx','sphinx','sphinx'),
        TagRepr('ssh','ssh','ssh'),
        TagRepr('stl','stl','stl'),
        TagRepr('svn','svn','svn'),
        TagRepr('tcp','tcp','tcp'),
        TagRepr('tdd','tdd','tdd'),
        TagRepr('test','test','test'),
        TagRepr('tornado','tornado','tornado'),
        TagRepr('uml','uml','uml'),
        TagRepr('unix','unix','unix'),
        TagRepr('vmware','vmware','vmware'),
        TagRepr('voip','voip','voip'),
        TagRepr('web','web','web'),
        TagRepr('xml','xml','xml'),
        TagRepr('zabbix','zabbix','zabbix'),
]
TAG_NAMES = [tag.name for tag in TAGS]
