#!/usr/bin/env python3

""" This file contains main configuration of Data Analyzer Chart.
"""

from collections import namedtuple

Skill = namedtuple('Tag', ['name', 'text', 'title'])

SKILLS = [Skill('c++', 'c++', 'cpp'),
          Skill('java', 'java', 'java'),
          Skill('python', 'python', 'python'),
          Skill('sap', 'sap', 'sap'),
          Skill('bash', 'bash', 'bash'),
          Skill('perl', 'perl', 'perl'),
          Skill('ruby', 'ruby', 'ruby'),
          Skill('javascript', 'javascript', 'javascript'),
          Skill('php', 'php', 'php'),
          Skill('1c', '1c', 'onec'),
          Skill('c#', 'c#', 'csharp'),
          Skill('algol','algol','algol'),
          Skill('ada','ada','ada'),
          Skill('basic','basic','basic'),
          Skill('cobol','cobol','cobol'),
          Skill('lisp','lisp','lisp'),
          Skill('erlang','erlang','erlang'),
          Skill('go','go','go'),
          Skill('groovy','groovy','groovy'),
          Skill('haskell','haskell','haskell'),
          Skill('lua','lua','lua'),
          Skill('matlab','matlab','matlab'),
          Skill('pascal','pascal','pascal'),
          Skill('rust','rust','rust'),
          Skill('scala','scala','scala'),
          Skill('smalltalk','smalltalk','smalltalk'),
          Skill('swift','swift','swift'),
          Skill('sql','sql','sql'),
          Skill('VBA','vba','vba'),
          Skill('agile','agile','agile'),
          Skill('ajax','ajax','ajax'),
          Skill('amd','amd','amd'),
          Skill('assembler','assembler','assembler'),
          Skill('awk','awk','awk'),
          Skill('backend','backend','backend'),
          Skill('canvas','canvas','canvas'),
          Skill('cmake','cmake','cmake'),
          Skill('cms','cms','cms'),
          Skill('css','css','css'),
          Skill('cuda','cuda','cuda'),
          Skill('cvs','cvs','cvs'),
          Skill('delphi','delphi','delphi'),
          Skill('django','django','django'),
          Skill('dll','dll','dll'),
          Skill('dns','dns','dns'),
          Skill('dom','dom','dom'),
          Skill('freebsd','freebsd','freebsd'),
          Skill('gcc','gcc','gcc'),
          Skill('gdb','gdb','gdb'),
          Skill('git','git','git'),
          Skill('github','github','github'),
          Skill('gps','gps','gps'),
          Skill('gpu','gpu','gpu'),
          Skill('ios','ios','ios'),
          Skill('innodb','innodb','innodb'),
          Skill('ipc','ipc','ipc'),
          Skill('iptables','iptables','iptables'),
          Skill('jira','jira','jira'),
          Skill('joomla','joomla','joomla'),
          Skill('jquery','jquery','jquery'),
          Skill('jruby','jruby','jruby'),
          Skill('json','json','json'),
          Skill('junit','junit','junit'),
          Skill('kanban','kanban','kanban'),
          Skill('linux','linux','linux'),
          Skill('lua','lua','lua'),
          Skill('mac','mac','mac'),
          Skill('memcached','memcached','memcached'),
          Skill('mysql','mysql','mysql'),
          Skill('nginx','nginx','nginx'),
          Skill('apache','apache','apache'),
          Skill('nix','nix','nix'),
          Skill('postgresql','postgresql','postgresql'),
          Skill('posix','posix','posix'),
          Skill('redis','redis','redis'),
          Skill('redmine','redmine','redmine'),
          Skill('saas','saas','saas'),
          Skill('scala','scala','scala'),
          Skill('scipy','scipy','scipy'),
          Skill('scrum','scrum','scrum'),
          Skill('search','search','search'),
          Skill('seo','seo','seo'),
          Skill('shell','shell','shell'),
          Skill('soap','soap','soap'),
          Skill('socket','socket','socket'),
          Skill('sphinx','sphinx','sphinx'),
          Skill('ssh','ssh','ssh'),
          Skill('stl','stl','stl'),
          Skill('svn','svn','svn'),
          Skill('tcp','tcp','tcp'),
          Skill('tdd','tdd','tdd'),
          Skill('test','test','test'),
          Skill('tornado','tornado','tornado'),
          Skill('uml','uml','uml'),
          Skill('unix','unix','unix'),
          Skill('vmware','vmware','vmware'),
          Skill('voip','voip','voip'),
          Skill('web','web','web'),
          Skill('xml','xml','xml'),
          Skill('zabbix','zabbix','zabbix'),
]
TAG_NAMES = [tag.name for tag in SKILLS]
